### ISSUE TITLE
Unable to create the user

### ISSUE THREAD

**Issue by wenkat** [GemHQ/round-py#3]
The following sequence of commands leads to an error. Any help is much appreciated. Creating the app and client was successful. I am testing with sandbox environment. Please let me know how to resolve this issue.

I am trying to run under the following environment.
Max OSX - 10.10
python 2.7.6 under virtual env.
round 0.7.4

 --- import round
 --- client = round.client()
/Users/blah/venv/lib/python2.7/site-packages/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
 --- client.authenticate_identify(api_token='token')
True
 --- client.users.create(email='EMAIL@ADDRE.SS', device_name='jingu',passphrase="user-chosen-passphrase")
/Users/blah/venv/lib/python2.7/site-packages/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/blah/venv/lib/python2.7/site-packages/round/users.py", line 91, in create
    raise e
patchboard.response.ResponseError: Unexpected response status: 400 - {"status":400,"message":"Bad Request","reason":[{"document":{"pointer":"#/default_wallet/network"},"schema":{"pointer":"urn:gem.co#/definitions/authorization_request/properties/user/properties/default_wallet/additionalProperties","definition":false}}]}

**Comment by joshua-bv** [comment]
Sorry for the troubles.  Could you try the following:

`$ pip install requests[security]`

looks like you might be hitting this issue:  https://stackoverflow.com/questions/29099404/ssl-insecureplatform-error-when-using-requests-package

Also round is up to version 0.8.0  so please `$ pip install round --upgrade`

if you'd like to get added to our slack channel where you can get live support, just email support@gem.co with the email address you'd like registered requesting slack access for python too.

**Comment by joshua-bv** [comment]
@wenkat let me know if you have any additional issues?

**Comment by wenkat** [comment]
Thanks for the quick help.  The steps mentioned above helps
