### ISSUE TITLE
Error with user.devices.create(name="Gem CLI")

### ISSUE THREAD

**Issue by jjtny1** [GemHQ/round-py#4]
I keep getting this error when i call user.devices.create(name=NAME):

raise Exception("Invalid WWW-Authenticate header: {}".format(string) )
Exception: Invalid WWW-Authenticate header:

**Comment by thedoctor** [comment]
First, make sure you have round version 0.8.0 (if you installed from github, current master is incompatible with the public Gem API – if you installed from pip, you should be fine) you can check quickly with `pip list round`

Once you're sure that's correct, if you still see the same issue, you probably haven't authenticated before making that call. For user.devices.create, you need to have Gem-Identify authentication, which means you need to call `client.authenticate_identify(api_token)` on the same `client` object that you used to create the `user` object, with the api_token you can find in the Gem console.

Let me know if this helps, or if it doesn't, reply with your source and I'll take a look.

**Comment by jjtny1** [comment]
Thanks. This fixed it for me. Appreciate it.

**Comment by thedoctor** [comment]
:+1:
